#!/usr/bin/env sh
# Defines a pre-push Git hook (enabled via the Husky library) which runs
# automated code formatting/linting fixes before a commit.

. "$(dirname -- "$0")/_/husky.sh"
set -euo pipefail

# Fix formatting
npm run fix:format

# Fix auto-fixable lints but ignore the rest. ESLint uses the exit code 1 for
# lint errors and 2 for fatal errors, so only exit code 2 should fail this
# script.
set +e
npm run fix:lint
if [ $? -eq 2 ]; then
    exit 1
fi
set -e

exit 0
